var a=100; var b=100; var c=100; var d=a+b+c; var e=300;
var f=Math.ceil(Math.random()*100);d=d-f;
var g=a-f; d=d-g;
console.log(300-d);
var h=Math.ceil(Math.random()*100); d=d-h;
var i=b-h; d=d-i;
console.log(300-d);
var l=Math.ceil(Math.random()*100); d=d-l;
var m=c-l; d=d-m;
console.log(300-d);
var n=Math.ceil(Math.random()*100); d=d-n;
var z=300-d;
console.log("control check " + z);
